(function(){
var h=false,j=null,m=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_tag_js_version:"gut",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",
google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",
google_rt:"rt",google_skip:"skip"};function da(){}da.prototype.Hb=function(){};da.prototype.Ib=function(){};da.prototype.Gb=function(){};var n=j;function ea(a){n&&n.Hb(a)}function fa(a){n&&n.Ib(a)}function ga(a){n&&n.Gb(a)}function r(){this.I=this.wb();this.qa=h;if(!this.I){(this.qa=this.bb())||fa("Browser does not allow cookies")}}r.prototype.ha="__gads=";r.prototype.R="GoogleAdServingTest=";r.prototype.ib=function(){return this.I};r.prototype.setCookieInfo=function(a){this.C=a._cookies_[0];if(this.C!=j){this.I=this.C._value_;this.Fb()}};
r.prototype.eb=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};r.prototype.db=function(a){if(this.I!=j||!this.qa)ea("Skipping fetch cookie call");else{var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+ha(a)+"&domain="+ha(c);ea("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")}};
r.prototype.bb=function(){document.cookie=this.R+"Good";var a=this.Ea(this.R),b=a=="Good";if(b){var c=this.eb(-1);document.cookie=this.R+"; expires="+c.toGMTString()}return b};r.prototype.wb=function(){var a=this.Ea(this.ha);a!=j?ea("Read first party cookie: "+a):fa("No first party cookie found");return a};r.prototype.Ea=function(a){var b=document.cookie,c=b.indexOf(a),d=j;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};
r.prototype.Fb=function(){if(this.C==j)fa("Skipping cookie creation: no cookie info");else if(this.I==j)ga("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.C._expires_);var b=this.C._domain_,c=this.ha+this.I+"; expires="+a.toGMTString()+"; path="+this.C._path_+"; domain=."+b;document.cookie=c;ea("Written cookie: "+c)}};function ia(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function ja(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=j}return b.toString()}else if(ka()){var c=j;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=j){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var la=la||{},s=this,na=function(a,b,c){var d=a.split("."),e=c||s,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);while(d.length&&(f=d.shift()))if(!d.length&&ma(b))e[f]=b;else e=e[f]?e[f]:(e[f]={})},oa=function(a,b){var c=a.split("."),d=b||s;for(var e;e=c.shift();)if(d[e])d=d[e];else return j;return d},t=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!pa(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b},qa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return m;return h};if(Object.prototype.propertyIsEnumerable)var pa=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):qa(a,b)};else pa=qa;var ma=function(a){return typeof a!="undefined"};
var ra=function(a){var b=t(a);return b=="array"||b=="object"&&typeof a.length=="number"},sa=function(a){return typeof a=="string"},ta=function(a){return t(a)=="function"},ua=function(a){var b=t(a);return b=="object"||b=="array"||b=="function"},xa=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(va)){var b=a[va];if(b)return b}a[va]||(a[va]=++wa);return a[va]},va="closure_hashCode_",wa=0,ya=function(a){var b=t(a);if(b=="object"||b=="array"){if(a.clone)return a.clone();var c=b=="array"?[]:{};for(var d in a)c[d]=
ya(a[d]);return c}return a},u=function(a,b){var c=a.Jb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.Lb||b;a=a.Kb||a;var e,f=b||s;e=c?function(){var g=Array.prototype.slice.call(arguments);g.unshift.apply(g,c);return a.apply(f,g)}:function(){return a.apply(f,arguments)};e.Jb=c;e.Lb=b;e.Kb=a;return e},za=Date.now||function(){return(new Date).getTime()},Aa=function(a,b,c){na(a,b,c)},v=function(a,b){function c(){}c.prototype=b.prototype;a.p=b.prototype;
a.prototype=new c;a.prototype.constructor=a};var Ba=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==j?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},Ca=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=sa(a)?a.split(""):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}},Da=function(a,b){var c=Ba(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};
var Ea=function(a){if(t(a)=="array")return a.concat();else{var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var Fa=function(a,b){this.x=ma(a)?a:0;this.y=ma(b)?b:0};Fa.prototype.clone=function(){return new Fa(this.x,this.y)};Fa.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var w=function(a,b){this.width=a;this.height=b};w.prototype.clone=function(){return new w(this.width,this.height)};w.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};w.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};w.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
w.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};w.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ga=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var Ha=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Na=function(a,b){if(b)return a.replace(Ia,"&amp;").replace(Ja,"&lt;").replace(Ka,"&gt;").replace(La,"&quot;");else{if(!Ma.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Ia,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ja,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Ka,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(La,"&quot;");return a}},Ia=/&/g,Ja=/</g,Ka=/>/g,La=/\"/g,Ma=/[&<>\"]/,Oa=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Qa=function(a,b){var c=0,d=Ha(String(a)).split("."),e=Ha(String(b)).split("."),f=Math.max(d.length,e.length);for(var g=0;c==0&&g<f;g++){var i=d[g]||"",k=e[g]||"",l=new RegExp("(\\d*)(\\D*)","g"),o=new RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(i)||["","",""],q=o.exec(k)||["","",""];if(p[0].length==0&&q[0].length==0)break;var x=p[1].length==0?0:parseInt(p[1],10),M=q[1].length==0?0:parseInt(q[1],
10);c=Pa(x,M)||Pa(p[2].length==0,q[2].length==0)||Pa(p[2],q[2])}while(c==0)}return c},Pa=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab,bb=function(){if(s.navigator)return s.navigator.userAgent;return j},cb=function(){var a=h,b=h,c=h,d=h,e=h,f=h,g=h,i=h,k=h,l="",o=bb();if(o){var p=s.navigator;a=o.indexOf("Opera")==0;b=!a&&o.indexOf("MSIE")!=-1;k=(c=!a&&o.indexOf("WebKit")!=-1)&&o.indexOf("Mobile")!=-1;e=(d=!a&&!c&&p.product=="Gecko")&&p.vendor=="Camino";var q,x;if(s.opera&&typeof s.opera.version=="function")q=s.opera.version();else{if(d)x=/rv\:([^\);]+)(\)|;)/;else if(b)x=/MSIE\s+([^\);]+)(\)|;)/;
else if(c)x=/WebKit\/(\S+)/;if(x){x.test(o);q=RegExp.$1}}l=p.platform||"";f=l.indexOf("Mac")!=-1;g=l.indexOf("Win")!=-1;i=l.indexOf("Linux")!=-1}Ra=a;Sa=b;Ta=d;Ua=e;Va=c;Wa=k;Xa=q;Ya=l;Za=f;$a=g;ab=i};cb();var db=Ra,y=Sa,jb=Ta,z=Va,kb=Wa;var A=function(a){return Qa(Xa,a)>=0};var lb;var mb=function(){lb||(lb=new B);return lb},ob=function(a){return a?new B(nb(a)):mb()};
var pb=function(a){return sa(a)?document.getElementById(a):a},qb=pb,sb=function(a,b){Ga(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in rb)a.setAttribute(rb[d],c);else a[d]=c})},rb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},tb=function(a){var b=a||s||window,c=b.document;if(z&&!A("500")&&
!kb){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new w(b.innerWidth,d)}var f=ob(c),g=f.gb()=="CSS1Compat"&&(!db||db&&A("9.50"))?c.documentElement:c.body;return new w(g.clientWidth,g.clientHeight)};var ub=function(a,b){a.appendChild(b)},vb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):j},wb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};
var xb=z&&Qa(Xa,"521")<=0,yb=function(a,b){if(typeof a.contains!="undefined"&&!xb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},nb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},zb=function(a){if(a&&typeof a.length=="number")if(ua(a))return typeof a.item=="function"||typeof a.item=="string";else if(ta(a))return typeof a.item=="function";return h},
B=function(a){this.n=a||s.document||document};B.prototype.X=function(){return this.n};B.prototype.xa=function(a){return sa(a)?this.n.getElementById(a):a};
B.prototype.Ua=function(a,b){if(y&&b&&(b.name||b.type)){var c=["<",a];b.name&&c.push(' name="',Na(b.name),'"');if(b.type){c.push(' type="',Na(b.type),'"');b=ya(b);delete b.type}c.push(">");a=c.join("")}var d=this.createElement(a);b&&sb(d,b);if(arguments.length>2){function e(i){if(i)this.appendChild(d,sa(i)?this.createTextNode(i):i)}for(var f=2;f<arguments.length;f++){var g=arguments[f];ra(g)&&!(ua(g)&&g.nodeType>0)?Ca(zb(g)?Ea(g):g,e,this):e.call(this,g)}}return d};B.prototype.createElement=function(a){return this.n.createElement(a)};
B.prototype.createTextNode=function(a){return this.n.createTextNode(a)};B.prototype.gb=function(){if(this.n.compatMode)return this.n.compatMode;if(z){var a=this.Ua("div",{style:"position:absolute;width:0;height:0;width:1"}),b=a.style.width=="1px"?"BackCompat":"CSS1Compat";return this.n.compatMode=b}return"BackCompat"};
B.prototype.wa=function(){var a=this.n,b,c;if(!z&&a.compatMode=="CSS1Compat"){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new Fa(b,c)};B.prototype.appendChild=ub;B.prototype.removeNode=vb;B.prototype.replaceNode=wb;B.prototype.contains=yb;var Ab,Bb=function(a,b){var c=nb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return j};
var Cb=function(a){return Bb(a,"position")||(a.currentStyle?a.currentStyle.position:j)||a.style.position},Db=function(a){var b;b=a?a.nodeType==9?a:nb(a):mb().X();if(y&&b.compatMode!="CSS1Compat")return b.body;return b.documentElement},Eb=function(a){var b=a.getBoundingClientRect();if(y){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},Fb=function(a){var b=nb(a),c=jb&&b.getBoxObjectFor&&Cb(a)=="absolute"&&(a.style.top==
""||a.style.left=="");if(typeof Ab=="undefined")Ab=Ua&&!A("1.8.0.11");var d=new Fa(0,0),e=Db(b);if(a==e)return d;var f=j,g;if(a.getBoundingClientRect&&!c){g=Eb(a);var i=ob(b).wa();d.x=g.left+i.x;d.y=g.top+i.y}else if(b.getBoxObjectFor&&!c&&!Ab){g=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=g.screenX-k.screenX;d.y=g.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(f!=a){d.x+=f.clientLeft||0;d.y+=f.clientTop||0}if(z&&Cb(f)=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;
break}f=f.offsetParent}while(f&&f!=a);if(db||z&&Cb(a)=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!db||f.tagName!="TR")d.y-=f.scrollTop;f=f.offsetParent}}if(jb&&a.getBoundingClientRect){var l=Cb(a);if(l=="static"||l=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},Gb=function(a){var b=new Fa;if(a.nodeType==1)if(a.getBoundingClientRect){var c=Eb(a);b.x=c.left;b.y=c.top}else{var d=ob(a).wa(),e=Fb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;
b.y=a.clientY}return b},Hb=function(a){var b=nb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=Bb(a,"fontFamily")||(a.currentStyle?a.currentStyle.fontFamily:j)||a.style.fontFamily;if(db&&ab)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Oa(c,"\"'")};var Ib=document,C=navigator,D=window;
function Jb(){var a=Ib.cookie,b=Math.round((new Date).getTime()/1000),c=D.google_analytics_domain_name,d=typeof c=="undefined"?Kb("auto"):Kb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,g=a.indexOf("__utmc="+d)>-1,i,k={};if(e){i=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&g?i[3]+"":D&&D.gaGlobal&&D.gaGlobal.sid?D.gaGlobal.sid:b+"";k.vid=i[0]+"."+i[1];k.from_cookie=m}else{k.sid=D&&D.gaGlobal&&D.gaGlobal.sid?D.gaGlobal.sid:b+"";k.vid=D&&D.gaGlobal&&D.gaGlobal.vid?
D.gaGlobal.vid:(Lb()^Mb()&2147483647)+"."+b;k.from_cookie=h}k.dh=d;k.hid=D&&D.gaGlobal&&D.gaGlobal.hid?D.gaGlobal.hid:Lb();return D.gaGlobal=k}function Lb(){return Math.round(Math.random()*2147483647)}
function Mb(){var a=Ib.cookie?Ib.cookie:"",b=D.history.length,c,d,e=[C.appName,C.version,C.language?C.language:C.browserLanguage,C.platform,C.userAgent,C.javaEnabled()?1:0].join("");if(D.screen)e+=D.screen.width+"x"+D.screen.height+D.screen.colorDepth;else if(D.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=Ib.referrer?Ib.referrer:"";c=e.length;while(b>0)e+=b--^c++;return Nb(e)}
function Nb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Kb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Ib.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Nb(a.toLowerCase())};var E=function(){};E.prototype.va=h;E.prototype.dispose=function(){if(!this.va){this.va=m;this.b()}};E.prototype.b=function(){};var Ob=function(a){if(/^\s*$/.test(a))return h;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Pb=function(a){String(a);if(Ob(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Qb=j,Rb=function(a){Qb||(Qb=new F);return Qb.serialize(a)},F=function(){};
F.prototype.serialize=function(a){var b=[];this.fa(a,b);return b.join("")};F.prototype.fa=function(a,b){switch(typeof a){case "string":this.Ha(a,b);break;case "number":this.Cb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==j){b.push("null");break}if(t(a)=="array"){this.Bb(a,b);break}this.Db(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Sb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};F.prototype.Ha=function(a,b){b.push('"',a.replace(/[\\\"\x00-\x1f\x80-\uffff]/g,function(c){if(c in Sb)return Sb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Sb[c]=e+d.toString(16)}),'"')};F.prototype.Cb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
F.prototype.Bb=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.fa(a[e],b);d=","}b.push("]")};F.prototype.Db=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.Ha(d,b);b.push(":");this.fa(e,b);c=","}}b.push("}")};var G="SETUP_ACK",H={},Ub=function(a,b){var c=b||Tb,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Tb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var I=function(){};v(I,E);I.prototype.f=0;var J=function(a){this.a=a;this.P=[];this.Qb=u(this.$a,this)};v(J,I);J.prototype.f=2;J.prototype.ba=h;J.prototype.Eb=0;J.prototype.connect=function(){if(this.a.s()==0){this.l=this.a.t;this.l.XPC_toOuter=u(this.ya,this)}else this.ma()};
J.prototype.ma=function(){var a=m;try{if(!this.l)this.l=window.frameElement;if(this.l&&this.l.XPC_toOuter){this.Ca=this.l.XPC_toOuter;this.l.XPC_toOuter.XPC_toInner=u(this.ya,this);a=h;this.send("tp",G);this.a.m()}}catch(b){}if(a){if(!this.Ma)this.Ma=u(this.ma,this);window.setTimeout(this.Ma,100)}};J.prototype.H=function(a){if(this.a.s()==0&&!this.a.g()&&a==G){this.Ca=this.l.XPC_toOuter.XPC_toInner;this.a.m()}else throw Error("Got unexpected transport message.");};
J.prototype.ya=function(a,b){if(!this.ba&&this.P.length==0)this.a.j(a,b);else{this.P.push({serviceName:a,payload:b});if(this.P.length==1)this.Eb=window.setTimeout(this.Qb,1)}};J.prototype.$a=function(){while(this.P.length){var a=this.P.shift();this.a.j(a.serviceName,a.payload)}};J.prototype.send=function(a,b){this.ba=m;this.Ca(a,b);this.ba=h};J.prototype.b=function(){J.p.b.call(this);this.l=this.Ca=j};var K=function(a){this.a=a;this.Q=this.a.c.ppu;this.Sb=this.a.c.lpu;this.da=[]},Vb,Wb;v(K,I);K.prototype.f=4;K.prototype.ea=0;K.prototype.w=h;K.prototype.Y=h;var Xb="googlexpc";K.prototype.M=function(){return Xb+"_"+this.a.name+"_msg"};K.prototype.L=function(){return Xb+"_"+this.a.name+"_ack"};K.prototype.connect=function(){if(!this.Y){this.Sa();this.Y=m}this.Oa()};K.prototype.Sa=function(){var a=this.M();this.D=this.U(a);this.Aa=window.frames[a];a=this.L();this.z=this.U(a);this.ia=window.frames[a]};
K.prototype.U=function(a){var b=mb().createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.Q+"#INITIAL";document.body.appendChild(b);return b};K.prototype.la=function(){var a=this.a.h.frames,b=a.length;for(var c=0;c<b;c++){var d;try{if(a[c]&&a[c].name)d=a[c].name}catch(e){}if(!!d){var f=d.split("_");if(f.length==3&&f[0]==Xb&&f[1]=="reconnect"){this.a.name=f[2];this.Ya();this.Y=h;break}}}};
K.prototype.Ya=function(){if(this.D){this.D.parentNode.removeChild(this.D);this.Aa=this.D=j}if(this.z){this.z.parentNode.removeChild(this.z);this.ia=this.z=j}};
K.prototype.Oa=function(){if(this.za(this.M())&&this.za(this.L())){this.pb=new Yb(this,this.a.h.frames[this.M()],u(this.ub,this));this.La=new Yb(this,this.a.h.frames[this.L()],u(this.tb,this));this.pa()}else{if(this.a.s()==1&&!this.Ub)this.Ub=this.U(Xb+"_reconnect_"+this.a.name);else this.a.s()==0&&this.la();window.setTimeout(u(this.connect,this),100)}};K.prototype.za=function(a){try{var b=this.a.h.frames[a];if(!b||b.location.href.indexOf(this.Sb)!=0)return h}catch(c){return h}return m};
K.prototype.pa=function(){var a=this.a.h.frames;if(a[this.L()]&&a[this.M()]){this.qb=new Zb(this.Q,this.Aa);this.S=new Zb(this.Q,this.ia);window.setTimeout(u(function(){this.qb.send("SETUP");this.w=this.Wb=m},this),100)}else{if(!this.Pa)this.Pa=u(this.pa,this);window.setTimeout(this.Pa,100)}};K.prototype.oa=function(){if(this.Ab&&this.Tb){this.a.m();if(this.K){for(var a=0,b;a<this.K.length;a++){b=this.K[a];this.a.j(b.service,b.payload)}delete this.K}}};
K.prototype.ub=function(a){if(a=="SETUP"){if(!!this.S){this.S.send(G);this.Ab=m;this.oa()}}else if(this.a.g()||this.Ab){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.S.send("ACK:"+e);this.ta(d)}else{var e=c.substring(0,b);this.S.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.Da=[];this.Da.push(d);if(f[0]==f[1]){this.ta(this.Da.join(""));delete this.Da}}}};
K.prototype.tb=function(a){if(a==G){this.w=h;this.Tb=m;this.oa()}else if(this.a.g())if(!!this.w){var b=parseInt(a.split(":")[1],10);if(b==this.ea){this.w=h;this.Ga()}}};K.prototype.Ga=function(){if(!(this.w||!this.da.length)){var a=this.da.shift();++this.ea;this.qb.send(this.ea+a);this.w=m}};K.prototype.ta=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.g()?this.a.j(c,d):(this.K||(this.K=[])).push({service:c,payload:d})};K.prototype.J=3800;
K.prototype.send=function(a,b){var c=a+":"+b;if(!y||b.length<=this.J)this.da.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.J),f=0,g=1;while(f<d){this.da.push(","+g+"/"+e+"|"+c.substr(f,this.J));g++;f+=this.J}}this.Ga()};K.prototype.b=function(){K.p.b.call(this);var a=$b;Da(a,this.pb);Da(a,this.La);this.pb=this.La=j;vb(this.D);vb(this.z);this.D=this.z=j;this.Aa=this.ia=j};
var $b=[],bc=function(){var a=h;try{for(var b=0,c=$b.length;b<c;b++)a=a||$b[b].receive()}catch(d){$b[b].d.a.rb();if(!$b.length)return}var e=za();if(a)Vb=e;var f=e-Vb<1000?10:100;Wb=window.setTimeout(ac,f)},ac=u(bc,K),cc=function(){Vb=za();Wb&&window.clearTimeout(Wb);Wb=window.setTimeout(ac,10)},Zb=function(a,b){this.Q=a;this.zb=b;this.sa=0};Zb.prototype.send=function(a){this.sa=++this.sa%2;var b=this.Q+"#"+this.sa+encodeURIComponent(a);try{if(z)this.zb.location.href=b;else this.zb.location.replace(b)}catch(c){}cc()};
var Yb=function(a,b,c){this.d=a;this.vb=b;this.Mb=c;this.Xa=this.vb.location.href.split("#")[0]+"#INITIAL";$b.push(this);cc()};Yb.prototype.receive=function(){var a=this.vb.location.href;if(a!=this.Xa){this.Xa=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Mb(decodeURIComponent(b))}return m}else return h};var L=function(a,b){E.call(this);this.ob=b;this.r=[];this.Va(a)};v(L,E);L.prototype.V=j;L.prototype.W=j;L.prototype.G=function(a){this.V=a};L.prototype.Ja=function(a){this.W=a};L.prototype.k=function(){if(this.r.length)return this.r.pop();return this.ra()};L.prototype.v=function(a){this.r.length<this.ob?this.r.push(a):this.ua(a)};L.prototype.Va=function(a){if(a>this.ob)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.r.push(this.ra())};
L.prototype.ra=function(){return this.V?this.V():{}};L.prototype.ua=function(a){if(this.W)this.W(a);else if(ta(a.dispose))a.dispose();else for(var b in a)delete a[b]};L.prototype.b=function(){L.p.b.call(this);var a=this.r;while(a.length)this.ua(a.pop());delete this.r};var N=function(a,b){this.type=a;this.currentTarget=this.target=b};v(N,E);N.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};N.prototype.F=h;N.prototype.ca=m;N.prototype.stopPropagation=function(){this.F=m};N.prototype.preventDefault=function(){this.ca=h};var O=function(a,b){a&&this.init(a,b)};v(O,N);O.prototype.type=j;O.prototype.target=j;O.prototype.relatedTarget=j;O.prototype.offsetX=0;O.prototype.offsetY=0;O.prototype.clientX=0;O.prototype.clientY=0;O.prototype.screenX=0;O.prototype.screenY=0;O.prototype.button=0;O.prototype.keyCode=0;O.prototype.charCode=0;O.prototype.ctrlKey=h;O.prototype.altKey=h;O.prototype.shiftKey=h;O.prototype.metaKey=h;O.prototype.i=j;
O.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:j;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.i=a;delete this.ca;delete this.F};O.prototype.stopPropagation=function(){this.F=m;if(this.i.stopPropagation)this.i.stopPropagation();else this.i.cancelBubble=m};
O.prototype.preventDefault=function(){this.ca=h;if(this.i.preventDefault)this.i.preventDefault();else{this.i.returnValue=h;try{this.i.keyCode=-1}catch(a){}}};O.prototype.fb=function(){return this.i};O.prototype.b=function(){O.p.b.call(this);this.i=j};var P=function(){},dc=0;P.prototype.$=j;P.prototype.listener=j;P.prototype.proxy=j;P.prototype.src=j;P.prototype.type=j;P.prototype.capture=j;P.prototype.handler=j;P.prototype.key=0;P.prototype.removed=h;P.prototype.na=h;P.prototype.init=function(a,b,c,d,e,f){if(ta(a))this.$=m;else if(a&&a.handleEvent&&ta(a.handleEvent))this.$=h;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.na=h;this.key=++dc;this.removed=h};
P.prototype.handleEvent=function(a){if(this.$)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var ec={},Q={},fc={},gc=new L(0,600);gc.G(function(){return{q:0}});gc.Ja(function(a){a.q=0});var hc=new L(0,600);hc.G(function(){return[]});hc.Ja(function(a){a.length=0;delete a.O;delete a.Ba});var ic=new L(0,600);ic.G(function(){var a=function(b){return lc.call(a.src,a.key,b)};return a});var mc=function(){return new P},nc=new L(0,600);nc.G(mc);
var oc=function(){return new O},pc=function(){var a=j;if(y){a=new L(0,600);a.G(oc)}return a},qc=pc(),rc="on",sc={},tc=function(a,b,c,d,e){if(b)if(t(b)=="array"){for(var f=0;f<b.length;f++)tc(a,b[f],c,d,e);return j}else{var g=!!d,i=Q;b in i||(i[b]=gc.k());i=i[b];if(!(g in i)){i[g]=gc.k();i.q++}i=i[g];var k=xa(a),l,o;if(i[k]){l=i[k];for(var f=0;f<l.length;f++){o=l[f];if(o.listener==c&&o.handler==e){if(o.removed)break;return l[f].key}}}else{l=i[k]=hc.k();i.q++}var p=ic.k();p.src=a;o=nc.k();o.init(c,
p,a,b,g,e);var q=o.key;p.key=q;l.push(o);ec[q]=o;fc[k]||(fc[k]=hc.k());fc[k].push(o);if(a.addEventListener){if(a==s||!a.Pb)a.addEventListener(b,p,g)}else a.attachEvent(uc(b),p);return q}else throw Error("Invalid event type");},vc=function(a,b,c,d,e){if(t(b)=="array"){for(var f=0;f<b.length;f++)vc(a,b[f],c,d,e);return j}var g=!!d,i=wc(a,b,g);if(!i)return h;for(var f=0;f<i.length;f++)if(i[f].listener==c&&i[f].capture==g&&i[f].handler==e)return xc(i[f].key);return h},xc=function(a){if(!ec[a])return h;
var b=ec[a];if(b.removed)return h;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==s||!c.Pb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(uc(d),e);var g=xa(c),i=Q[d][f][g];if(fc[g]){var k=fc[g];Da(k,b);k.length==0&&delete fc[g]}b.removed=m;i.Ba=m;yc(d,f,g,i);delete ec[a];return m},yc=function(a,b,c,d){if(!d.O)if(d.Ba){for(var e=0,f=0;e<d.length;e++)if(d[e].removed)nc.v(d[e]);else{if(e!=f)d[f]=d[e];f++}d.length=f;d.Ba=h;if(f==0){hc.v(d);delete Q[a][b][c];
Q[a][b].q--;if(Q[a][b].q==0){gc.v(Q[a][b]);delete Q[a][b];Q[a].q--}if(Q[a].q==0){gc.v(Q[a]);delete Q[a]}}}},wc=function(a,b,c){var d=Q;if(b in d){d=d[b];if(c in d){d=d[c];var e=xa(a);if(d[e])return d[e]}}return j},uc=function(a){if(a in sc)return sc[a];return sc[a]=rc+a},Ac=function(a,b,c,d){var e=1,f=Q;if(b in f){f=f[b];if(c in f){f=f[c];var g=xa(a);if(f[g]){var i=f[g];if(i.O)i.O++;else i.O=1;try{var k=i.length;for(var l=0;l<k;l++){var o=i[l];if(o&&!o.removed)e&=zc(o,d)!==h}}finally{i.O--;yc(b,c,
g,i)}}}}return Boolean(e)},zc=function(a,b){var c=a.handleEvent(b);a.na&&xc(a.key);return c},lc=function(a,b){if(!ec[a])return m;var c=ec[a],d=c.type,e=Q;if(!(d in e))return m;e=e[d];var f;if(y){var g=b||oa("window.event"),i=m in e;if(i){if(g.keyCode<0||g.returnValue!=undefined)return m;Bc(g)}xa(c.src);var k=qc.k();k.init(g,this);f=m;try{if(i){var l=hc.k();for(var o=k.currentTarget;o;o=o.parentNode)l.push(o);for(var p=l.length-1;!k.F&&p>=0;p--){k.currentTarget=l[p];f&=Ac(l[p],d,m,k)}for(var p=0;!k.F&&
p<l.length;p++){k.currentTarget=l[p];f&=Ac(l[p],d,h,k)}}else f=zc(c,k)}finally{if(l){l.length=0;hc.v(l)}k.dispose();qc.v(k)}return f}var q=new O(b,this);try{f=zc(c,q)}finally{q.dispose()}return f},Bc=function(a){var b=h;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=m}if(b||a.returnValue==undefined)a.returnValue=m};var R=function(a){this.a=a;this.Rb=this.a.c.pru;this.sb=this.a.c.ifrid;z&&Cc()};v(R,I);if(z){var Dc=[],Ec=0,Cc=function(){Ec||(Ec=window.setTimeout(function(){Fc()},1000))},Fc=function(a){var b=za(),c=a||3000;while(Dc.length&&b-Dc[0].timestamp>=c){var d=Dc.shift().iframeElement;vb(d)}Ec=window.setTimeout(Gc,1000)},Gc=function(){Fc()}}R.prototype.f=3;R.prototype.connect=function(){this.send("tp","SETUP")};R.prototype.H=function(a){if(a=="SETUP"){this.send("tp",G);this.a.m()}else a==G&&this.a.m()};
R.prototype.send=function(a,b){if(y){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=Hc}else{var d=document.createElement("iframe");z?Dc.push({timestamp:za(),iframeElement:d}):tc(d,"load",Hc)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.Rb;f+="#"+this.a.name;if(this.sb)f+=","+this.sb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var Hc=function(){vb(this);this.xpcOnload=j};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);H[a].j(d,decodeURIComponent(e))};R.prototype.b=function(){R.p.b.call(this);z&&Fc(0)};var S=function(a,b){this.a=a;this.aa=b||"*"};v(S,I);S.prototype.f=1;var Ic=h,Kc=function(){if(!Ic){tc(window.postMessage?window:document,"message",Jc,h,S);Ic=m}},Jc=function(a){var b=a.fb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return h;var e=b.substring(0,c),f=b.substring(c+1,d),g=b.substring(d+1),i=H[e];if(i){i.j(f,g);return m}for(var k in H){var l=H[k];if(l.s()==1&&!l.g()&&f=="tp"&&g=="SETUP"){l.name=e;H[e]=l;H[k]=j;l.j(f,g);return m}}return h};
S.prototype.H=function(a){switch(a){case "SETUP":if(!this.Vb){this.Vb=m;this.send("tp",G)}break;case G:this.a.m();break}};S.prototype.connect=function(){Kc();this.T()};S.prototype.T=function(){if(!this.a.g()){this.send("tp","SETUP");window.setTimeout(u(this.T,this),100)}};S.prototype.send=function(a,b){var c=this.a.h;if(!!c){var d=c.postMessage?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,this.aa)};this.send(a,b)}};
S.prototype.b=function(){S.p.b.call(this);vc(window.postMessage?window:document,"message",Jc,h,S)};var T=function(a){this.a=a;this.Na=a.at||"";this.yb=a.rat||"";Lc();this[Mc]=this.N;this[Nc]=this.Ta};v(T,I);
var Oc="GRPC____NIXVBS_wrapper",Pc="GRPC____NIXVBS_get_wrapper",Mc="GRPC____NIXJS_handle_message",Nc="GRPC____NIXJS_create_channel",Qc="GRPC____NIXVBS_container",Lc=function(){if(!window.nix_setup_complete){var a="Class "+Oc+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Mc+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Nc+"(channel)\nEnd Sub\nPublic Sub "+Qc+"()\n End Sub\nEnd Class\n Function "+Pc+"(transport, auth)\nDim wrap\nSet wrap = New "+Oc+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Pc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=m}catch(b){}}};T.prototype.f=6;T.prototype.u=h;T.prototype.o=j;T.prototype.connect=function(){this.a.s()==0?this.ka():this.ja()};
T.prototype.ka=function(){if(!this.u){var a=this.a.t;try{a.contentWindow.opener=window[Pc](this,this.Na);this.u=m}catch(b){}this.u||window.setTimeout(u(this.ka,this),100)}};T.prototype.ja=function(){if(!this.u){try{var a=window.opener;if(a&&Qc in a){this.o=a;var b=this.o.GetAuthToken();if(b!=this.yb)return;this.o.CreateChannel(window[Pc](this,this.Na));this.u=m;this.a.m()}}catch(c){return}this.u||window.setTimeout(u(this.ja,this),100)}};
T.prototype.Ta=function(a){this.o=a;var b=this.o.GetAuthToken();b!=this.yb||this.a.m()};T.prototype.N=function(a,b){function c(){this.a.j(a,b)}window.setTimeout(u(c,this),1)};T.prototype.send=function(a,b){this.o.SendMessage(a,b)};T.prototype.b=function(){T.p.b.call(this);this.o=j};var U=function(a){E.call(this);this.c=a;this.name=this.c.cn||Ub(10);this.Ia={};H[this.name]=this;tc(window,"unload",Rc)};v(U,E);U.prototype.d=j;U.prototype.ga=1;U.prototype.g=function(){return this.ga==2};U.prototype.h=j;U.prototype.t=j;U.prototype.Ka=function(a){this.h=a};
U.prototype.Wa=function(){if(!this.d){if(!this.c.tp)if(ta(document.postMessage)||ta(window.postMessage))this.c.tp=1;else if(jb)this.c.tp=2;else if(y&&this.c.pru)this.c.tp=3;else if(y)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.d=new S(this,this.c.ph);break;case 6:this.d=new T(this);break;case 2:this.d=new J(this);break;case 3:this.d=new R(this);break;case 4:this.d=new K(this);break}if(!this.d)throw Error("CrossPageChannel: No suitable transport found!");}};
U.prototype.Za=h;U.prototype.Ra=h;U.prototype.connect=function(a){this.Ob=a;if(this.Za)this.Ra=m;else{if(this.c.ifrid)this.t=sa(this.c.ifrid)?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.t){var b=this.t.contentWindow;b||(b=window.frames[this.c.ifrid]);this.Ka(b)}if(!this.h)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.Ka(window.parent);this.Wa();this.d.connect()}};
U.prototype.close=function(){if(!!this.g()){this.ga=3;this.d.dispose();this.d=j}};U.prototype.m=function(){if(!this.g()){this.ga=2;this.Ob()}};U.prototype.rb=function(){this.close()};U.prototype.xb=function(a,b,c){this.Ia[a]={name:a,callback:b,jsonEncoded:!!c}};U.prototype.send=function(a,b){if(!!this.g())if(this.h.closed)this.close();else{if(ua(b))b=Rb(b);this.d.send(a,b)}};U.prototype.j=function(a,b){if(!a||a=="tp")this.d.H(b);else if(this.g()){var c=this.Ia[a];if(c){if(c.jsonEncoded)try{b=Pb(b)}catch(d){return}c.callback(b)}}};
U.prototype.s=function(){return window.parent==this.h?1:0};U.prototype.b=function(){U.p.b.call(this);this.close();this.t=this.h=j;delete this.Ia;H[this.name]=j};var Rc=function(){for(var a in H){var b=H[a];b&&b.dispose()}};var Sc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var V=function(a,b){this.B=a.width;this.A=a.height;this.Nb=b;this.aa=this.hb(a.src,document);this.Z=h;this.e=a;this.nb(this.jb())};V.prototype.jb=function(){var a={};a.ifrid=this.e.id;a.pu=this.e.src;a.ph=this.aa;a.cn=this.Nb;a.ppu=Sc(this.aa);a.lpu=Sc();return a};V.prototype.nb=function(a){this.a=new U(a);this.a.xb("expandable_ad",u(this.N,this));this.a.connect(function(){});window.setTimeout(u(this.lb,this),30000)};
V.prototype.lb=function(){if(this.a&&!this.a.g()){this.a.d.connect=function(){};if(this.a.d.f==1)this.a.d.T=function(){};if(this.a.d.f==4)this.a.d.la=function(){};this.a.d.dispose();this.a.dispose()}};V.prototype.hb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,g=f.indexOf("/");if(g<0)g=f.indexOf("?");if(d&&g>0)f=f.substring(0,g);return e+"//"+f};
V.prototype.N=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.mb(b);else c=="collapse"&&this.kb()};V.prototype.Fa=function(a){this.a.send("expandable_ad",a)};V.prototype.mb=function(a){if(!this.Z){var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.ab(b,c);this.cb(b,c,f);this.Fa("ok_expand_w"+b+"_h"+c+"_d"+f)}};
V.prototype.kb=function(){if(!!this.Z){this.Qa();this.Fa("ok_collapse_w"+this.B+"_h"+this.A)}};V.prototype.Qa=function(){this.e.style.width=this.B+"px";this.e.style.height=this.A+"px";this.e.style.left="0";this.e.style.top="0";this.e.style.zIndex=j;this.e.parentNode.style.zIndex=j;this.Z=h};
V.prototype.cb=function(a,b,c){this.e.style.position="absolute";this.e.style.width=a+"px";this.e.style.height=b+"px";this.e.style.zIndex=9999;this.e.parentNode.style.zIndex=9999;if(a>this.B&&(c==0||c==3))this.e.style.left="-"+(a-this.B)+"px";if(b>this.A&&(c==1||c==0))this.e.style.top="-"+(b-this.A)+"px";this.Z=m};
V.prototype.ab=function(a,b){var c=Gb(this.e),d=tb(window),e=a-this.B,f=b-this.A,g=c.y,i=f>g,k=d.height-(c.y+this.A),l=i||k>=g,o=c.x,p=e>o,q=d.width-(c.x+this.B),x=p||q>=o,M=0;if(l&&x)M=2;else if(l&&!x)M=3;else if(!l&&x)M=1;else if(!l&&!x)M=0;return M};
var Tc=function(){},Wc=function(a,b,c,d,e){if(!a||!b||c<=0||d<=0)return j;var f=Ub(10);b=Uc(b,c,d,f);var g=Vc(a,b,c,d,e);return new V(g,f)},Uc=function(a,b,c,d){var e=mb().X();return a+(a.indexOf("?")==-1?"?":"&")+"w="+b+"&h="+c+"&xpc="+d+"&p="+escape(e.location.protocol+"//"+e.location.host)},Vc=function(a,b,c,d,e){var f='<ins style="width:'+c+"px;height:"+d+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none"><iframe allowtransparency=true frameborder=0 height='+
d+" hspace=0 id="+a+' marginheight=0 marginwidth=0 name=google_ads_frame scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe></ins>",g=ob(),i=g.xa(e);if(i)i.innerHTML=f;else g.X().write(f);return g.xa(a)};Aa("ExpandableAdSlot",V);Aa("ExpandableAdSlotFactory",Tc);var W="",Xc=h;function Yc(a){return a!=j?'"'+a+'"':'""'}function ha(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ba[a]||ca[a]||j,d=b[a];X(c,d)}function Z(a,b){b!=j&&X(a,ha(b))}function $(a){var b=window,c=ba[a]||ca[a]||j,d=b[a];Z(c,d)}function Zc(a,b){var c=window,d=ba[a]||ca[a]||j,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}
function $c(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function ad(a){if(!!a.google_enable_first_party_cookie){if(n==j)n=new da;if(a._GA_googleCookieHelper==j)a._GA_googleCookieHelper=new r;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.db(bd(a.google_ad_client))}}}function bd(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function cd(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function dd(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}function ed(){var a=y&&A("6")&&!A("8"),b=jb&&A("1.8.1"),c=z&&A("525");if($a&&(a||b||c))return m;else if(Za&&(c||b))return m;else if(ab&&b)return m;return h}
function fd(a,b){var c=a.google_allow_expandable_ads;if(c!=j&&c==h||!b.body||a.google_ad_output!="html"||gd(a,b)||hd(a)||id(a.google_ad_format)||typeof a.google_ad_height!="number"&&String(parseInt(a.google_ad_height,10))!=a.google_ad_height||typeof a.google_ad_width!="number"&&String(parseInt(a.google_ad_width,10))!=a.google_ad_width||!ed())return h;return m}
function jd(){var a=Math.random(),b=0,c=ia("0.03",0.03),d=2*c;if(a<c)return"30143019";if(a<d)return"30143020";b=d;c=ia("0.03",0.03);d=2*c;c+=b;d+=b;if(a<c)return"30143021";if(a<d)return"30143022";return""}function kd(){var a=Math.random(),b=ia("0.01",0.01),c=2*b;if(a<b)return"6083027";if(a<c)return"6083026";return""}function ld(a){a.google_allow_expandable_ads=h;a.google_expandable_iframe=h}var md=Math.random()<0.0010;
function nd(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function od(a,b,c,d){var e=dd(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Yc(pd(c))+"></"+f+">");else if(a.google_ad_output=="html")if(b.body&&(a.google_expandable_iframe||W.indexOf("30143020")!=-1)){var g=a.google_container_id||d||j;a["google_expandable_ad_slot"+e]=Wc("google_ads_frame"+e,pd(c),parseInt(a.google_ad_width,
10),parseInt(a.google_ad_height,10),g)}else{var i='<iframe name="google_ads_frame" width='+Yc(a.google_ad_width)+" height="+Yc(a.google_ad_height)+" frameborder="+Yc(a.google_ad_frameborder)+" src="+Yc(pd(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';if(Xc&&W.indexOf("30143022")!=-1)i='<ins style="width:'+parseInt(a.google_ad_width,10)+"px;height:"+parseInt(a.google_ad_height,10)+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none">'+
i+"</ins>";a.google_container_id?qd(a.google_container_id,b,i):b.write(i)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+Yc(pd(c))+"></"+f+">");if(md){var k=rd(a)+"/pagead/gen_204?id=ifjs2&token="+a.google_correlator+"&output="+ha(a.google_ad_output)+"&url="+ha(a.google_page_url);nd(a,k)}}
function sd(a){for(var b in ba)a[b]=j;for(var b in ca)b=="google_correlator"||(a[b]=j);a.google_allow_expandable_ads=j;a.google_container_id=j;a.google_expandable_iframe=j;a.googlen_tag_js_version=j}function hd(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function id(a){return a&&a.indexOf("_sdo")!=-1}
function td(a){var b=j,c=window,d=document,e=aa,f=c.google_ad_format,g=rd(c),i;if(c.google_cpa_choice!=b){c.google_ad_url=g+"/cpa/ads?";i=escape(bd(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if(id(f)){c.google_ad_url=g+"/pagead/sdo?";i=escape(cd(c.google_ad_client))}else{c.google_ad_url=g+"/pagead/ads?";i=escape(bd(c.google_ad_client))}c.google_ad_url+=
"client="+i;Y("google_ad_host");Y("google_ad_host_tier_id");var k=c.google_num_slots_by_client,l=c.google_num_slots_by_channel,o=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(id(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return h}else if(hd(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return h}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){o[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return h}else if(c.google_num_ad_slots>6&&q=="")return h}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var x=c.google_ad_client;if(k[x])k[x]+=1;else{k[x]=1;k.length+=1}if(o[q])if(!id(f)){Z("prev_fmts",o[q].toLowerCase());k.length>1&&X("slot",k[x])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());id(f)||(o[q]=o[q]?o[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var M="",jc=c.google_ad_channel.split(ud);for(var eb=0;eb<jc.length;eb++){var fb=jc[eb];if(l[fb])M+=fb+"+";else l[fb]=1}Z("pv_ch",M)}if(c.google_ad_host_channel){$("google_ad_host_channel");var Cd=
vd(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",Cd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.ib());$("google_page_url");Zc("google_color_bg",e);Zc("google_color_text",e);Zc("google_color_link",e);Zc("google_color_url",e);Zc("google_color_border",e);Zc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");Xc=fd(c,d);if(!Xc)ld(c);else if(c.google_expandable_iframe===h)ld(c);else if(i in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=m;else if(!(c.google_expandable_iframe==m)){var gb=jd();if(gb){if(W!="")W+=",";W+=gb}gb!="30143020"&&ld(c)}X("eid",W);var kc=
c.google_allow_expandable_ads;if(kc!=j)kc?X("ea","1"):X("ea","0");Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_ui_version");
$("google_tag_js_version");$("google_only_ads_with_video");$("google_disable_video_autoplay");if(a){Z("ff",Hb(a));var hb=Fb(a),ib=tb();if(hb&&ib){Z("biw",ib.width);Z("bih",ib.height);Z("adx",hb.x);Z("ady",hb.y)}}Jb();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");$c(c);md&&X("gen_204","ifjs2");return m}
function vd(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var g=c[f].split(ud);b[f]||(b[f]={});var i="";for(var k=0;k<g.length;k++){var l=g[k];if(b[f][l])i+="+"+l;else b[f][l]=1}i=i.slice(1);e[f]=i;if(i!="")d=f}var o="";if(d>-1){for(var f=0;f<d;f++)o+=e[f]+"|";o+=e[d]}return o}
function wd(){var a=window,b=document;ad(a);var c=kd();if(c){if(W!="")W+=",";W+=c}var d;if(c!="6083027"){var e="google_temp_span";if(!qb(e)){b.write("<span id="+e+"></span>");d=qb(e)}}var f=td(d);d&&vb(d);if(!!f){od(a,b,a.google_ad_url);sd(a)}}function pd(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function xd(){wd();return m}
function gd(a,b){if(a.top.location==b.location)return h;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return h}return m}
function yd(a){var b=window,c=j,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(id(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;zd(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ja();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function Ad(a){if(a in Bd)return Bd[a];return Bd[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var Bd={};function ka(){return Ad("msie")&&!window.opera}
function Dd(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(g){}}return b}function Ed(){var a=window,b=Dd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function Fd(a,b){for(var c in b)a["google_"+c]=b[c]}
function Gd(a,b){if(!b)return a.location;return a.referrer}function Hd(a,b){if(!b&&a.google_referrer_url==j)return"0";else if(b&&a.google_referrer_url==j)return"1";else if(!b&&a.google_referrer_url!=j)return"2";else if(b&&a.google_referrer_url!=j)return"3";return"4"}function Id(a,b,c,d){a.page_url=Gd(c,d);a.page_location=j}function Jd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Gd(c,d)||"EMPTY"}
function Kd(a,b){var c={},d=gd(a,b);c.iframing=Hd(a,d);!!a.google_page_url?Jd(c,a,b,d):Id(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:j;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Ld(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=j;b.page_url=c;b.page_location=a.location;b.last_modified_time=j;b.referrer_url=c;return b}
function zd(a,b){var c;c=a.google_page_url==j&&Md[b.domain]?Ld(b):Kd(a,b);Fd(a,c)}function qd(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Md={};Md["ad.yieldmanager.com"]=m;var ud=/[+, ]/;window.google_render_ad=wd;var Nd={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Od(a){var b=a.google_page_location||a.google_page_url;if(!b)return h;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=h;if(e.length>=3)f=e[e.length-3]in Nd;if(e.length>=2)f=f||e[e.length-2]in Nd;return f}
function Pd(a,b,c){if(Od(a)){a.google_new_domain_checked=1;return h}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return m}}return h}function rd(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Od(a)&&a.google_new_domain_enabled==1)return b;return c};function Qd(a,b){var c="script",d=Pd(a,b,ia("1",0.01));d&&ka()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}Ed();yd(xd);Qd(window,document);
})()
