//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TimeM.rc
//
#define IDOK                            1
#define IDC_BTN_SELALL                  3
#define ID_BTN_REDO                     3
#define ID_BTN_UNDO                     4
#define ID_BTN_UNDO2                    5
#define ID_BTN_REDO2                    6
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDD_PLAYER_FORM                 101
#define IDS_TASKLIST_WND                101
#define IDS_COL_TITLE_NO                102
#define IDS_COL_TITLE_START             103
#define IDS_COL_TITLE_END               104
#define IDS_COL_TITLE_CONTENT           105
#define IDS_COL_TITLE_CHCOUNT           106
#define IDS_CHKERRINFO1                 107
#define IDS_CHKERRINFO2                 108
#define IDS_CHKERRINFO3                 109
#define IDS_CHKERRINFO4                 110
#define IDS_CHKERRINFO5                 111
#define IDS_CHKERRINFO6                 112
#define IDS_CHKERRINFO7                 113
#define IDS_CMDTYPE_FILENAME            114
#define IDS_CMDTYPE_EDITNAME            115
#define IDS_CMDTYPE_TITLENAME           116
#define IDS_CMDTYPE_TOOLNAME            117
#define IDS_CMDTYPE_VIDEONAME           118
#define IDR_POPUP_EDIT                  119
#define IDS_SEL_SINGLELINE_LR           119
#define IDS_NOTFOUND_OTHERS             120
#define IDS_TOOLARGEFILE                121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_REPLTMPL_SAVEPROMPT         126
#define IDS_DOC_SAVEPROMPT              127
#define IDR_MAINFRAME                   128
#define IDD_TITLE_FORM                  129
#define IDS_NOZIPSET                    129
#define IDR_TimeMTYPE                   130
#define IDS_POS_COLNAME                 131
#define IDS_INTERVAL_COLNAME            132
#define IDD_DLG_IMPORTOPTION            133
#define IDS_NOMATCHINTERVAL             133
#define IDD_DLG_INSERTCOUNT             134
#define IDS_REPLACE_WND                 134
#define IDD_DLG_TIME_INPUT              135
#define IDS_INSERTSEQ                   135
#define IDD_DLG_EXTRATIME_INPUT         136
#define IDS_COL_TITLE_TIMELEN           136
#define IDD_DLG_FIND                    137
#define IDS_CR_COMMENT                  137
#define IDD_DLG_SPLITTITLE              138
#define IDS_NOTMATCHSP                  138
#define IDD_DLG_REPLACE                 139
#define IDS_WITHVALIDSPLIT              139
#define IDB_BMP_LISTCHK                 140
#define IDS_NOSELITEMFOUND              140
#define IDD_DLG_CMBN_DOC                141
#define IDS_MARKPOSERROR                141
#define IDR_MENU_LISTCONTEXT            142
#define IDS_CURPOSERROR                 142
#define IDD_DLG_TITLECOMBINE            143
#define IDS_FOUNDAUTOSAVE               143
#define IDD_DLG_COMPARETITLE            144
#define IDS_AUTOSAVEREADERROR           144
#define IDD_DLG_CHECKVALID              145
#define IDS_SAVESTDTIPS                 145
#define IDD_DLG_OPTIONS                 146
#define IDS_SAVETRANSTIPS               146
#define IDD_DLG_EXPORTOPTION            147
#define IDD_DLG_CPSEL                   150
#define IDD_DLG_SSASETTINGS             151
#define IDD_DLG_MIN_INTERVAL            152
#define IDD_DLG_LISTINTERVAL            153
#define IDS_COL_TITLE_LINENUM           154
#define IDD_DLG_FILTER                  155
#define IDS_OUTPUT_WND                  157
#define IDB_BMP_LOGOABOUT               157
#define IDS_PROPERTIES_WND              158
#define IDD_DLG_SPLITFILE               158
#define IDD_DLG_ANYSPLITTITLE           159
#define IDS_CHSTITLEDEFAULT             160
#define ID_VIEW_TASKPANE                171
#define ID_VIEW_OUTPUTWND               172
#define ID_VIEW_PROPERTIESWND           173
#define IDR_THEME_MENU                  200
#define IDR_MENU_CBLISTCONTEXT          201
#define IDS_EDIT_MENU                   306
#define IDB_BMP_TASKS                   310
#define IDD_DLG_SAVESETTING             313
#define IDR_MENU_COMBINE_EXT            314
#define IDD_DLG_RANGETITLE              315
#define IDC_STATIC_FRM                  1000
#define IDC_EDIT_FILESTD                1001
#define IDC_EDIT_TIME_OFFSET            1001
#define IDC_EDIT_TOFIND                 1001
#define IDC_EDIT_LINECOUNT              1001
#define IDC_EDIT_START                  1001
#define IDC_EDIT_TARGETTEXT             1001
#define IDC_EDIT_SPLITNUM               1001
#define IDC_CHK_NEW                     1001
#define IDC_EDIT_FILETRANS              1002
#define IDC_EDIT_TIME_LEN               1002
#define IDC_EDIT_END                    1002
#define IDC_EDIT_TIME_DEFLEN            1002
#define IDC_EDIT_SPLITTIME              1002
#define IDC_STATIC_TTLEN                1002
#define IDC_RBTN_SEL                    1003
#define IDC_RBTN_ALL                    1004
#define IDC_EDIT_TITLE                  1004
#define IDC_CHK_AUTOBAK                 1004
#define IDC_RBTN_MARKS                  1005
#define IDC_EDIT_BAKPATH                1005
#define IDC_RBTN_SINGLELINE             1006
#define IDC_EDIT_CHARCOUNT              1006
#define IDC_EDIT_BAKMAX                 1006
#define IDC_RBTN_AFTER                  1006
#define IDC_RBTN_SPLITNULLLINE          1007
#define IDC_SPIN_LINECOUNT              1007
#define IDC_EDIT_TIMEDELAY              1007
#define IDC_RBTN_FORWARD                1008
#define IDC_BTN_EDITSTD                 1008
#define IDC_CHK_CASESENSE               1009
#define IDC_RBTN_BACK                   1009
#define IDC_BTN_RELOADSTD               1009
#define IDC_EDIT_FROM                   1009
#define IDC_RBTN_UPDIRECT               1010
#define IDC_BTN_EDITTRANS               1010
#define IDC_EDIT_TO                     1010
#define IDC_RBTN_DNDIRECT               1011
#define IDC_RBTN_SPLITBYNUM             1011
#define IDC_BTN_RELOADSTD2              1011
#define IDC_BTN_RELOADTRANS             1011
#define IDC_CHK_SRTASSOCIATE            1011
#define IDC_RBTN_SPLITBYTIME            1012
#define IDC_CHK_ASSASSOCIATE            1012
#define IDC_SPIN_SPLITNUM               1013
#define IDC_CHK_SSAASSOCIATE2           1013
#define IDC_CHK_SSAASSOCIATE            1013
#define IDC_CB_EFFECTPREV               1013
#define IDC_EDIT_RESULTTEXT             1014
#define IDC_SPIN_SPLITTIME              1014
#define IDC_COMBO2                      1014
#define IDC_CB_EFFECTPOST               1014
#define IDC_RBTN_SELECTED               1016
#define IDC_LIST_RPLITEMS               1019
#define IDC_BTN_LOADTPL                 1021
#define IDC_BTN_SAVETPL                 1022
#define IDC_BTN_ADDITEM                 1023
#define IDC_BTN_REMOVE                  1024
#define IDC_CHK_INCCHS                  1025
#define IDC_CHK_USEBATCH                1026
#define IDC_CHK_INCENG                  1027
#define IDC_EDIT_TPLFILE                1028
#define IDC_BTN_CLOSETPL                1029
#define IDC_LIST_STDTITLE               1030
#define IDC_LIST_TRANSTITLE             1031
#define IDC_BTN_BROWSTD                 1032
#define IDC_BTN_BROWTRANS               1033
#define IDSAVE                          1034
#define IDC_CHK_SYNCSCROLL              1035
#define IDC_BTN_SNAPSEL                 1036
#define IDC_CHECK1                      1037
#define IDC_BTN_SNAPAUTO                1037
#define IDSAVE2                         1037
#define IDC_CHECK2                      1038
#define IDC_BTN_TO_LEFTEMPTY            1038
#define IDC_CHECK3                      1039
#define IDC_BTN_TO_RIGHTEMPTY           1039
#define IDC_CHECK4                      1040
#define IDC_CHECK5                      1041
#define IDC_CHECK6                      1042
#define IDC_CHECK7                      1043
#define IDC_EDIT1                       1044
#define IDC_EDIT2                       1045
#define IDC_EDIT3                       1046
#define IDC_EDIT4                       1047
#define IDC_BUTTON1                     1048
#define IDC_BUTTON2                     1049
#define IDC_BUTTON3                     1050
#define IDC_BUTTON4                     1051
#define IDC_BUTTON5                     1052
#define IDC_BUTTON6                     1053
#define IDC_BUTTON7                     1054
#define IDC_LIST1                       1055
#define IDC_LIST_COMMANDS               1056
#define IDC_LB_CMDHK                    1057
#define IDC_HK_CTRL                     1058
#define IDC_EDIT_USEDCOMMAND            1061
#define IDC_CHK_AUTOSAVE                1063
#define IDC_LIST_FILEFMT                1064
#define IDC_CHK_ZIPPACK                 1066
#define IDC_CHK_UNICODE                 1068
#define IDC_EDIT_ENGNAME                1073
#define IDC_EDIT_CHSNAME                1074
#define IDC_EDIT_CHTNAME                1075
#define IDC_BTN_BROWZIPTOOL             1076
#define IDC_EDIT_ZIPTOOL                1077
#define IDC_CB_CPLIST                   1078
#define IDC_BTN_CLEAROVERLAP            1079
#define IDC_STATIC_SINFO                1080
#define IDC_STATIC_SSASTYLES            1081
#define IDC_EDIT_SINFO                  1082
#define IDC_EDIT_SSASTYLES              1083
#define IDC_STATIC_EFFECTCODEPREV       1084
#define IDC_EDIT_EFFECTPREV             1085
#define IDC_LIST_INTERVAL               1086
#define IDC_STATIC_EFFECTCODEENXT       1086
#define IDC_EDIT_SUBTITLE               1087
#define IDC_EDIT_EFFECTNEXT             1087
#define IDC_RBTN_EMPTYLINE              1088
#define IDC_STATIC_EVENTS               1088
#define IDC_RBTN_SEQFILL                1089
#define IDC_EDIT_EVENTS                 1089
#define IDC_CHK_INITTIME                1090
#define IDC_CHK_REMOVEEMPTY             1091
#define IDC_CHK_REMOVESPECCHAR          1092
#define IDC_EDIT_SPECCHAR               1093
#define IDC_EDIT_CRTEXT                 1094
#define IDC_BTN_SETASS                  1099
#define IDC_BTN_BROW                    1100
#define IDC_EDIT_OUTPATH                1101
#define IDC_BTN_REMOVESPLITOR           1104
#define IDC_RBTN_SINGLANG               1105
#define IDC_RBTN_DUALLANG               1106
#define ID_VIEW_APPLOOK_WIN_2000        32772
#define ID_VIEW_APPLOOK_OFF_XP          32773
#define ID_VIEW_APPLOOK_WIN_XP          32774
#define ID_VIEW_APPLOOK_OFF_2003        32775
#define ID_VIEW_APPLOOK_VS_2005         32776
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32777
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32778
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32779
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32780
#define ID_HIDE_ASSCODE                 32783
#define ID__32786                       32786
#define ID__32787                       32787
#define ID_CB_ALL                       32788
#define ID_CB_FROMTO                    32789
#define ID_32792                        32792
#define ID_FILE_EXPORTFU                32793
#define ID_FILE_IMPORT                  32827
#define ID_FILE_APPEND                  32828
#define ID_FILE_EXPORT                  32829
#define ID_SETTINGS_HOTKEY              32835
#define ID_VIDEO_OPEN                   32836
#define ID_VIDEO_CLOSE                  32837
#define ID_VIDEO_PLAY_PAUSE             32838
#define ID_VIDEO_STOP                   32839
#define ID_VIDEO_BACK1S                 32841
#define ID_VIDEO_FORWARD_S1             32842
#define ID_VIDEO_FORWARD1S              32843
#define ID_VIDEO_FORWARD5S              32844
#define ID_VIDEO_BACK5S                 32845
#define ID_VIDEO_RATE10                 32848
#define ID_VIDEO_RATE50                 32849
#define ID_VIDEO_RATE100                32850
#define ID_VIDEO_RATE200                32851
#define ID_VIDEO_RATE400                32852
#define ID_VIDEO_RATEUSER               32853
#define ID_VIDEO_STEPONE                32854
#define ID_VIDEO_SYNCTITLE              32855
#define ID_TOOL_PREPROC                 32856
#define ID_TOOL_CMBYTIME                32857
#define ID_TOOL_CMBYUSER                32858
#define ID_TOOL_ADDAUTHOR               32859
#define ID_TOOL_COMPARE                 32860
#define ID_TOOL_CHECK                   32861
#define ID_TITLE_INSERT                 32865
#define ID_TITLE_MULTIINSERT            32866
#define ID_TITLE_EXTEND                 32867
#define ID_TITLE_DELETE                 32868
#define ID_TITLE_EXCHANGE               32869
#define ID_TITLE_BREAKBYUSER            32871
#define ID_TITLE_ZEROTIME               32872
#define ID_TITLE_EMPTYCONTENT           32873
#define ID_TITLE_MOVETIME               32874
#define ID_TITLE_CBONELINE              32875
#define ID_TITLE_CBMULTILINE            32876
#define ID_TITLE_SNAPLINE               32877
#define ID_TITLE_SNAPAFTER              32878
#define ID_TITLE_SNAPALL                32879
#define ID_TITLE_SNAPLINEEND            32880
#define ID_TITLE_SNAPLINESTART          32881
#define ID_TITLE_SNAPPREVMARK           32882
#define ID_TITLE_SNAPBETWEENTWOMARK     32883
#define ID_TITLE_TO25FPS                32884
#define ID_TITLE_FROM25FPS              32885
#define ID_EDIT_FINDNEXT                32888
#define ID_EDIT_SORTSTART               32912
#define ID_EDIT_SORTEND                 32913
#define ID_EDIT_SORTCONTENT             32914
#define ID_EDIT_SORTLEN                 32915
#define ID_EDIT_MARK                    32920
#define ID_EDIT_GOTOMARK                32922
#define ID_TITLE_AUTOSNAP               32928
#define ID_TITLE_SNAPNEXT               32929
#define ID_OPTION_SETTINGS              32934
#define ID_DEFAULT_CHARSET              32939
#define ID_BIG5_CHARSET                 32940
#define ID_GB2312_CHARSET               32941
#define ID_OPTIONS_ASSSETTINGS          32944
#define ID_TITLE_PREVLINE               32953
#define ID_TITLE_NEXTLINE               32954
#define ID_EDIT_GOTOPREVMARK            32962
#define ID_TITLE_DELBYCOND              32966
#define ID_TITLE_SINGLELINETITLE        32968
#define ID_SUBTITLE_REL1                32977
#define ID_SUBTITLE_REL2                32978
#define ID_SUBTITLE_REL3                32979
#define ID_SUBTITLE_REL4                32980
#define ID_SUBTITLE_REL5                32981
#define ID_SUBTITLE_REL6                32982
#define ID_SUBTITLE_REL7                32983
#define ID_HELP_UPLOAD                  32984
#define ID_HELP_HOME                    32985
#define ID_HELP_LESSON                  32986
#define ID_FILE_SPLITTO                 32988
#define ID_OPTION_AUTOSAVE              32990
#define ID_VIEW_TOOLBAR                 0xE800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
